//PUT http://localhost:3001/api/persons/4
//PATCH http://localhost:3001/api/persons/4
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "new name",
    "number": "12345"
}